name: Run tests with coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate_commit:
    name: Validate Code and Publish Coverage
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/main' }}
    permissions:
      id-token: write      # required for dependabot PRs
      pull-requests: write # required for dependabot PRs
      contents: read       # required for dependabot PRs
    steps:
      - uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24.*'

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: 'kind'
          config: integration_tests/kind.yaml

      - name: Deploy Ingress NGINX Controller
        run: kubectl apply -f https://kind.sigs.k8s.io/examples/ingress/deploy-ingress-nginx.yaml

      - name: Wait for Ingress NGINX Controller to be ready
        run: |
          kubectl wait --namespace ingress-nginx \
            --for=condition=ready pod \
            --selector=app.kubernetes.io/component=controller \
            --timeout=120s

      - name: Deploy apps
        run: kubectl apply -f https://kind.sigs.k8s.io/examples/ingress/usage.yaml

      - name: Wait for apps to be ready
        run: |
          kubectl wait --for=condition=ready pod -l app=foo --timeout=120s
          kubectl wait --for=condition=ready pod -l app=bar --timeout=120s

      - name: Check kind cluster
        run: |
          kubectl cluster-info
          kubectl get nodes
          kind get kubeconfig --name kind

      - name: Test connectivity to apps
        run: |
          curl --fail http://localhost:55555/foo
          curl --fail http://localhost:55555/bar

      - name: Get logs from application pods
        run: |
          kubectl logs -l app=foo
          kubectl logs -l app=bar

      - name: Check Format
        run: gofmt -d ./

      - name: Verify dependencies
        run: go mod verify

      - name: Install dependencies
        run: go mod vendor

      - name: Run go vet
        run: go vet ./...

      - name: Build
        run: go build -v ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.0
